### ISSUE TITLE
图片托管

### ISSUE THREAD

**Issue by williambj1** [xzhih/hackintosh-list#10]
@xzhih 您好！
请问图片托管能直接链接到Github仓库吗
谢谢🙏

**Comment by xzhih** [comment]
可以，不过还是建议用 https://sm.ms/，或者其他例如微博图床

**Comment by williambj1** [comment]
不好意思，我还有一个问题
图片的分辨率要求是多少，400x225吗？
是不是1920x1080没法显示？
谢谢🙏

**Comment by xzhih** [comment]
图片大小没有要求，GIF都可以，只是图片太大会导致加载慢，我建议是720p然后压缩一下啦

**Comment by williambj1** [comment]
THX!
