### ISSUE TITLE
神舟战神K4极速版（i5版本）

### ISSUE THREAD

**Issue by Maxcj** [xzhih/hackintosh-list#3]
"Device": "Hasee-K4极速版",
"Author": "Maxcj",
"CPU": "i5-4210M",
"Audio": "Realtek ALC282",
"OS": "10.12.6 10.13.5 10.13.6 10.14+",
"Link": "https://github.com/Maxcj/Hasee-OS-X"

**Comment by xzhih** [comment]
已添加 8e44fda
